name: Generate Snake Game

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository content
      uses: actions/checkout@v3

    - name: Generate Snake Game from GitHub user contributions
      uses: Platane/snk@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        output: dist/snake.svg

    - name: Upload Snake Game SVG
      uses: actions/upload-artifact@v3
      with:
        name: snake-game
        path: dist/snake.svg
